name: Generate snake

on:
  schedule:
    - cron: "23 3 * * *"   # ежедневно 06:23 по Киеву
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: blvckcatswag
          outputs: |
            output/snake.svg
            output/snake-dark.svg?palette=github-dark

      - name: Push snake to repo
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
